package me.dreamteam.tardis;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


public class GUI extends javax.swing.JFrame {

    // Variables declaration - do not modify
    static javax.swing.JDesktopPane GameFrame;
    static javax.swing.JPanel GamePanel;
    static javax.swing.JPanel Master;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAch;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHTP;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayGame;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnPrev1;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnShip1;
    private javax.swing.JButton btnShip2;
    private javax.swing.JButton btnShip3;
    private javax.swing.JLabel imgShip1;
    private javax.swing.JLabel imgShip2;
    private javax.swing.JLabel imgShip3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelLogoSmall2;
    private javax.swing.JLabel labelLogoSmall3;
    private javax.swing.JPanel panelAch;
    private javax.swing.JPanel panelChar;
    private javax.swing.JPanel panelHTP;
    private javax.swing.JPanel panelMain;
    private javax.swing.JProgressBar pbAch1;
    private javax.swing.JProgressBar pbAch2;
    private javax.swing.JProgressBar pbAch3;
    private javax.swing.JLabel txtAchDesc1;
    private javax.swing.JLabel txtAchDesc2;
    private javax.swing.JLabel txtAchDesc3;
    private javax.swing.JLabel txtAchTitle;
    private javax.swing.JLabel txtAchTitle1;
    private javax.swing.JLabel txtAchTitle2;
    private javax.swing.JLabel txtAchTitle3;
    private javax.swing.JLabel txtEnterUsername;
    private javax.swing.JLabel txtHTPTitle;
    private javax.swing.JTextPane txtpUsername;
    static javax.swing.JPanel panelGame;
    static java.awt.Canvas Canvas;

    /**
     * Creates new form GameUI
     */
    public GUI() {
        systemLF();
        UIManager.put("Button.focus", Color.white);
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    public static void systemLF() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Master = new javax.swing.JPanel();
        GameFrame = new javax.swing.JDesktopPane();
        panelGame = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        btnPlayGame = new javax.swing.JButton();
        btnHTP = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panelChar = new javax.swing.JPanel();
        txtEnterUsername = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpUsername = new javax.swing.JTextPane();
        btnShip1 = new javax.swing.JButton();
        btnShip2 = new javax.swing.JButton();
        btnShip3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnPlay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAch = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        imgShip1 = new javax.swing.JLabel();
        imgShip2 = new javax.swing.JLabel();
        imgShip3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jSeparator4 = new javax.swing.JSeparator();
        panelAch = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        labelLogoSmall2 = new javax.swing.JLabel();
        txtAchTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtAchTitle1 = new javax.swing.JLabel();
        txtAchDesc1 = new javax.swing.JLabel();
        pbAch1 = new javax.swing.JProgressBar();
        jSeparator5 = new javax.swing.JSeparator();
        pbAch2 = new javax.swing.JProgressBar();
        txtAchDesc2 = new javax.swing.JLabel();
        txtAchTitle2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        pbAch3 = new javax.swing.JProgressBar();
        txtAchDesc3 = new javax.swing.JLabel();
        txtAchTitle3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        panelHTP = new javax.swing.JPanel();
        btnPrev1 = new javax.swing.JButton();
        labelLogoSmall3 = new javax.swing.JLabel();
        txtHTPTitle = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        Canvas = new java.awt.Canvas();
        GamePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Utils.gameName + Utils.version);
        setMaximumSize(new java.awt.Dimension(500, 650));
        setMinimumSize(new java.awt.Dimension(500, 650));
        setResizable(false);
        setName("mainframe");

        ImageIcon icon = new ImageIcon(Utils.iconURL);
        setIconImage(icon.getImage());

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        setLocation(x, y);

        Master.setBackground(new java.awt.Color(0, 0, 0));
        Master.setForeground(new java.awt.Color(255, 255, 255));
        Master.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Master.setMaximumSize(new java.awt.Dimension(500, 650));
        Master.setMinimumSize(new java.awt.Dimension(500, 650));
        Master.setName("Master"); // NOI18N
        Master.setPreferredSize(new java.awt.Dimension(500, 650));
        Master.setVerifyInputWhenFocusTarget(false);
        Master.setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(0, 0, 0));
        panelMain.setMaximumSize(new java.awt.Dimension(500, 650));
        panelMain.setMinimumSize(new java.awt.Dimension(500, 650));
        panelMain.setName("panelMain"); // NOI18N

        btnPlayGame.setBackground(new java.awt.Color(0, 0, 0));
        btnPlayGame.setFont(new java.awt.Font("Minecraftia", 1, 36)); // NOI18N
        btnPlayGame.setText("Play Game");
        btnPlayGame.setToolTipText("");
        btnPlayGame.setOpaque(false);
        btnPlayGame.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ship.png"))); // NOI18N
        btnPlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayGameActionPerformed(evt);
            }
        });

        btnHTP.setBackground(new java.awt.Color(0, 0, 0));
        btnHTP.setFont(new java.awt.Font("Minecraftia", 0, 24)); // NOI18N
        btnHTP.setText("How to Play");
        btnHTP.setBorder(btnPlayGame.getBorder());
        btnHTP.setFocusPainted(false);
        btnHTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTPActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(0, 0, 0));
        btnAbout.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        btnAbout.setText("Website");
        btnAbout.setFocusPainted(false);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(0, 0, 0));
        btnQuit.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setFocusPainted(false);
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/splash.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
                panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnHTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                                                .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnPlayGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelMainLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
                panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(btnHTP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        Master.add(panelMain, "panelMain");

        panelChar.setBackground(new java.awt.Color(0, 0, 0));
        panelChar.setForeground(new java.awt.Color(255, 255, 255));
        panelChar.setName("panelChar"); // NOI18N

        txtEnterUsername.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        txtEnterUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtEnterUsername.setText("Please enter your username");

        jScrollPane1.setBorder(null);

        txtpUsername.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        txtpUsername.setAutoscrolls(false);
        txtpUsername.setMargin(new java.awt.Insets(8, 8, 8, 8));
        txtpUsername.getDocument().putProperty("filterNewlines", Boolean.TRUE);
        txtpUsername.addKeyListener(new java.awt.event.KeyAdapter() {
           public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpUsernameKeyPressed(evt);
            }
         });
        jScrollPane1.setViewportView(txtpUsername);

        btnShip1.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip1.setText("PEN-15");
        btnShip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShip1ActionPerformed(evt);
            }
        });

        btnShip2.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip2.setText("FALCON");
        btnShip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShip2ActionPerformed(evt);
            }
        });

        btnShip3.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip3.setText("CICADA");
        btnShip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShip3ActionPerformed(evt);
            }
        });

        btnPlay.setFont(new java.awt.Font("Minecraftia", 1, 18)); // NOI18N
        btnPlay.setText("Play >>");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAch.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnAch.setText("Achievements & Unlocks");
        btnAch.setActionCommand("\n");
        btnAch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAchActionPerformed(evt);
            }
        });

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/logo-small.png"))); // NOI18N
        labelLogo.setText("jLabel3");

        imgShip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ship.png"))); // NOI18N
        imgShip1.setText("jLabel4");

        imgShip2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ship2.png"))); // NOI18N
        imgShip2.setText("jLabel4");

        imgShip3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ship3.png"))); // NOI18N
        imgShip3.setText("jLabel4");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setBorder(null);
        jTextPane1.setBorder(BorderFactory.createEmptyBorder());
        jTextPane1.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("Choose a ship from above");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextPane1.setEnabled(false);
        jTextPane1.setFocusCycleRoot(false);
        jTextPane1.setFocusable(false);
        jTextPane1.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jTextPane1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout panelCharLayout = new javax.swing.GroupLayout(panelChar);
        panelChar.setLayout(panelCharLayout);
        panelCharLayout.setHorizontalGroup(
                panelCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCharLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                        .addGroup(panelCharLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1)
                                        .addComponent(jSeparator2)
                                        .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelCharLayout.createSequentialGroup()
                                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCharLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(imgShip1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(113, 113, 113)
                                                .addComponent(imgShip2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(imgShip3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCharLayout.createSequentialGroup()
                                                .addComponent(btnShip1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnShip2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                                .addComponent(btnShip3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelCharLayout.createSequentialGroup()
                                                .addComponent(txtEnterUsername)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jSeparator4))
                                .addContainerGap())
        );
        panelCharLayout.setVerticalGroup(
                panelCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCharLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelLogo)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtEnterUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(imgShip1)
                                        .addComponent(imgShip2)
                                        .addComponent(imgShip3))
                                .addGap(18, 18, 18)
                                .addGroup(panelCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnShip1)
                                        .addComponent(btnShip2)
                                        .addComponent(btnShip3))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAch, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                                .addContainerGap())
        );

        Master.add(panelChar, "panelChar");

        panelAch.setBackground(new java.awt.Color(0, 0, 0));
        panelAch.setForeground(new java.awt.Color(255, 255, 255));
        panelAch.setMaximumSize(new java.awt.Dimension(500, 650));
        panelAch.setMinimumSize(new java.awt.Dimension(500, 650));
        panelAch.setName("panelAch"); // NOI18N

        btnPrev.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        btnPrev.setText("<< Return to Previous Menu");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        labelLogoSmall2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/logo-small.png"))); // NOI18N
        labelLogoSmall2.setText("jLabel3");

        txtAchTitle.setFont(new java.awt.Font("Minecraftia", 1, 24)); // NOI18N
        txtAchTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtAchTitle.setText("Achievements & Unlocks ");
        txtAchTitle.setToolTipText("");

        txtAchTitle1.setFont(new java.awt.Font("Minecraftia", 1, 14)); // NOI18N
        txtAchTitle1.setForeground(new java.awt.Color(255, 255, 255));
        txtAchTitle1.setText("Explorer");

        txtAchDesc1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txtAchDesc1.setForeground(new java.awt.Color(255, 255, 255));
        txtAchDesc1.setText("Travel a distance of 1000m");

        pbAch1.setToolTipText("");

        txtAchDesc2.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txtAchDesc2.setForeground(new java.awt.Color(255, 255, 255));
        txtAchDesc2.setText("Travel a distance of 5000m");

        txtAchTitle2.setFont(new java.awt.Font("Minecraftia", 1, 14)); // NOI18N
        txtAchTitle2.setForeground(new java.awt.Color(255, 255, 255));
        txtAchTitle2.setText("Voyager");

        txtAchDesc3.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txtAchDesc3.setForeground(new java.awt.Color(255, 255, 255));
        txtAchDesc3.setText("Achievement 3 Text");

        txtAchTitle3.setFont(new java.awt.Font("Minecraftia", 1, 14)); // NOI18N
        txtAchTitle3.setForeground(new java.awt.Color(255, 255, 255));
        txtAchTitle3.setText("Achievement 3");

        javax.swing.GroupLayout panelAchLayout = new javax.swing.GroupLayout(panelAch);
        panelAch.setLayout(panelAchLayout);
        panelAchLayout.setHorizontalGroup(
                panelAchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAchLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelAchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAchLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(labelLogoSmall2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAchLayout.createSequentialGroup()
                                                .addGroup(panelAchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator5)
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnPrev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(pbAch2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(pbAch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pbAch3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAchLayout.createSequentialGroup()
                                                                .addGroup(panelAchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txtAchDesc2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtAchTitle2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtAchDesc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtAchTitle1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtAchDesc3, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtAchTitle3, javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAchLayout.createSequentialGroup()
                                .addContainerGap(54, Short.MAX_VALUE)
                                .addComponent(txtAchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
        );
        panelAchLayout.setVerticalGroup(
                panelAchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAchLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelLogoSmall2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAchTitle)
                                .addGap(21, 21, 21)
                                .addComponent(txtAchTitle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAchDesc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbAch1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAchTitle2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAchDesc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbAch2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAchTitle3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAchDesc3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbAch3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addContainerGap())
        );

        Master.add(panelAch, "panelAch");

        panelHTP.setBackground(new java.awt.Color(0, 0, 0));
        panelHTP.setForeground(new java.awt.Color(255, 255, 255));
        panelHTP.setMaximumSize(new java.awt.Dimension(500, 650));
        panelHTP.setMinimumSize(new java.awt.Dimension(500, 650));
        panelHTP.setName("panelHTP"); // NOI18N

        btnPrev1.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        btnPrev1.setText("<< Return to Previous Menu");
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });

        labelLogoSmall3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/logo-small.png"))); // NOI18N
        labelLogoSmall3.setText("jLabel3");

        txtHTPTitle.setFont(new java.awt.Font("Minecraftia", 1, 24)); // NOI18N
        txtHTPTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtHTPTitle.setText("      How to Play");
        txtHTPTitle.setToolTipText("");

        javax.swing.GroupLayout panelHTPLayout = new javax.swing.GroupLayout(panelHTP);
        panelHTP.setLayout(panelHTPLayout);
        panelHTPLayout.setHorizontalGroup(
                panelHTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHTPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelHTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHTPLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(labelLogoSmall3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHTPLayout.createSequentialGroup()
                                                .addGroup(panelHTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnPrev1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHTPLayout.createSequentialGroup()
                                .addContainerGap(54, Short.MAX_VALUE)
                                .addComponent(txtHTPTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
        );
        panelHTPLayout.setVerticalGroup(
                panelHTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHTPLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelLogoSmall3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHTPTitle)
                                .addGap(421, 421, 421)
                                .addComponent(btnPrev1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addContainerGap())
        );

        Master.add(panelHTP, "panelHTP");

        GameFrame.setMaximumSize(new java.awt.Dimension(500, 650));
        GameFrame.setMinimumSize(new java.awt.Dimension(500, 650));
        GameFrame.setName("GameFrame"); // NOI18N

        GamePanel.setName("GamePanel"); // NOI18N

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
                GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 500, Short.MAX_VALUE)
        );
        GamePanelLayout.setVerticalGroup(
                GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 650, Short.MAX_VALUE)
        );

        GamePanel.setBounds(0, 0, 500, 650);
        GameFrame.add(GamePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
                panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGameLayout.createSequentialGroup()
                                .addComponent(GameFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGameLayout.setVerticalGroup(
                panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGameLayout.createSequentialGroup()
                                .addComponent(GameFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        Master.add(panelGame, "panelGameC");
        panelGame.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Master, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Master, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void btnShip1ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextPane1.setText("The PEN-15 is a medium speed ship and is manufactured by Surex Industries.\nThe ship can fire from the hull if ammo is present.");
        // Bold and Font
        btnShip3.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip2.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip1.setFont(new java.awt.Font("Minecraftia", 1, 18)); // NOI18N
        // Colour
        btnShip1.setForeground(new java.awt.Color(255, 0, 1));
        btnShip2.setForeground(new java.awt.Color(0, 0, 0));
        btnShip3.setForeground(new java.awt.Color(0, 0, 0));
    }

    private void btnShip2ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextPane1.setText("The FALCON is a fast ship and is manufactured by Hawk Industries.\nThe ship can fire from the the sides if ammo is present.");
        btnShip3.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip2.setFont(new java.awt.Font("Minecraftia", 1, 18)); // NOI18N
        btnShip1.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N

        // Colour
        btnShip1.setForeground(new java.awt.Color(0, 0, 0));
        btnShip2.setForeground(new java.awt.Color(255, 0, 1));
        btnShip3.setForeground(new java.awt.Color(0, 0, 0));
    }

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {
        //CardLayout cl = (CardLayout)(Master.getLayout());
        //cl.show(Master, "panelGameC");
        dispose();
        GProperties.release = true;
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)(Master.getLayout());
        cl.previous(Master);
    }

    private void btnShip3ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextPane1.setText("The CICADA is a slow ship and is manufactured by Anon Industries.\nThe ship can fire from the the sides if ammo is present.");
        btnShip3.setFont(new java.awt.Font("Minecraftia", 1, 18)); // NOI18N
        btnShip2.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        btnShip1.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        // Colour
        btnShip1.setForeground(new java.awt.Color(0, 0, 0));
        btnShip2.setForeground(new java.awt.Color(0, 0, 0));
        btnShip3.setForeground(new java.awt.Color(255, 0, 1));
    }

    private void btnAchActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)(Master.getLayout());
        cl.next(Master);
    }

     private void txtpUsernameKeyPressed(java.awt.event.KeyEvent evt) {
        txtpUsername.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),
                "doNothing");
        txtpUsername.getInputMap().put(KeyStroke.getKeyStroke("SPACE_BAR"),
                "doNothing");
       txtpUsername.getInputMap().put(KeyStroke.getKeyStroke("released SPACE"),
                "doNothing");
        txtpUsername.getInputMap().put(KeyStroke.getKeyStroke("TAB"),
                "doNothing");
    }

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String url = "http://the-dreamteam.co.uk";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }

    private void btnPlayGameActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)(Master.getLayout());
        cl.show(Master, "panelChar");
    }

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)(Master.getLayout());
        cl.show(Master, "panelMain");
    }

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) (Master.getLayout());
        cl.show(Master, "panelChar");
    }

    private void btnHTPActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) (Master.getLayout());
        cl.show(Master, "panelHTP");
    }

}




